### ISSUE TITLE
Segfaults when Working with Layouts

### ISSUE THREAD

**Issue by MggMuggins** [Longhanks/qlift#1]
Alright. I'm having some issues when I'm playing around with layouts. This Gist: https://gist.github.com/MggMuggins/dea7198df879e8e74c1ad8ae0aeb6cd4 is a good example. Depending on when I initialize my layouts, I get segfaults, and then I get more when I add things to the layouts. It makes absolutely no sense.

**Comment by Longhanks** [comment]
Change line 18 (`self.layout.add(item: self.v_layout`) to `self.layout.add(layout: self.v_layout)` and it should should work™.

I'm not sure why the underlying code crashes though. According to Qt, QLayouts inherit QLayoutItem. Might have to take a closer look.

**Comment by MggMuggins** [comment]
Thanks. I didn't notice that in the API source.

Does swift have a documentation generator of some kind? Embedding some doc-comments into the API and running a doc generator over it could be potentially really useful.

**Comment by Longhanks** [comment]
At least for Xcode, it allows some subset of markup to be used: http://nshipster.com/swift-documentation/

But I'm afraid there's no real solution for Linux or the Swiftt Package Manager yet. The code so far hasn't been documented greatly (apart from QliftUIParser, which is arguably the most complex class until now)-
