### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by MihaelIsaev** [Longhanks/qlift#4]
Hello!

Do you have any plans to support compilation for Windows?
As far as I know since Swift 5.3 windows will be supported officially 🙂 
Would be really cool if you could describe how to compile an app for windows 🙏

**Comment by Longhanks** [comment]
Support is currently not possible because Swift on Windows does not yet ship swiftpm. I will add support as soon as swiftpm is available.

**Comment by daniele-niero** [comment]
SPM (Swift Package Manager) is available on Windows.

Also, C++ interoperability is now available. Would be cool to push this library further to be truly cross platform and with c++ interoperability.
